apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: replicaset-demo
    tier: frontend
    component: frontend
spec:
  replicas: 1 # Ensures exactly 1 pod is running at all times
  selector:
    # This must match the labels in the template below
    matchLabels:
      project: roboshop
      purpose: replicaset-demo
      tier: frontend
      component: frontend
  # This is pod defintion, pod is subset of replicaset
  template:
    metadata:
      # Labels used by the ReplicaSet to identify its pods
      labels:
        project: roboshop
        purpose: replicaset-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.23-perl